### ISSUE TITLE
请问android授权页logo怎么替换

### ISSUE THREAD

**Issue by pingxiaodou** [253CL/CLShanYan_Flutter#1]
setLogoImgPath 使用flutter内的图片好像不行，请问应该如何设置

**Comment by pingxiaodou** [comment]
需要放到android/drawable 文件夹下， 主要不要加文件后缀。如在android/drawable/logo.png，设置setLogoImgPath="logo" 即可

**Comment by z759341385** [comment]
资源在打包安卓的时候 可能会因为原生没使用被删除  处理方法：https://blog.csdn.net/u014780554/article/details/80973154
